services:
  - type: web
    name: paws-crypto-api
    runtime: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: URL
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    autoDeploy: true
    healthCheckPath: /api/health
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 3
      targetMemoryPercent: 80
