services:
  - type: web
    name: paws-crypto-api
    runtime: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: URL
        value: https://crypto-airdrop-paws.netlify.app
      - key: VITE_APP_URL
        value: https://crypto-airdrop-paws.netlify.app
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: VITE_TELEGRAM_BOT_TOKEN
        value: 7395999208:AAHD-3nVoIWFDF1uAGOWGCTmmMut4J2AXzM
