services:
  - type: web
    name: paws-crypto-api
    runtime: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: URL
        sync: false
      - key: VITE_APP_URL
        sync: false
      - key: PORT
        sync: false
      - key: NODE_ENV
        value: production
